import { DiscoveryConfig, DiscoveryConfigV2, DiscoveryStrategy } from './discovery-types';

/**
 * Legacy V1 strategies used by the active scheduler.
 * This preserves 100% backward compatibility and isolates development of V2.
 */
export const legacyDiscoveryStrategies: DiscoveryStrategy[] = [
  { type: 'keyword', keyword: 'vegetable chopper', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'sink organizer', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'car phone holder', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'car vacuum cleaner', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'motion sensor light', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'smart plug', pages: 1, pageSize: 20 },
];

/**
 * Editorial V2 Category Library.
 * Contains 30 categories with exactly 20 unique, safe keywords each (600 total).
 */
export const discoveryLibraryV2: DiscoveryConfigV2 = {
  categoriesPerRun: 3,
  defaultKeywordsPerCategory: 1,
  categories: [
    {
      id: 'kitchen',
      displayName: 'Kitchen Gadgets',
      hebrewLabel: 'מטבח',
      emoji: '🍳',
      description: 'שימושי למטבח הביתי, הכנת אוכל, בישול ואפייה',
      weight: 10,
      enabled: true,
      keywords: [
        'vegetable chopper',
        'oil spray bottle',
        'garlic press rocker',
        'silicone spatula set',
        'magnetic kitchen timer',
        'digital food scale',
        'knife sharpener tool',
        'meat thermometer digital',
        'milk frother handheld',
        'silicone baking mat',
        'herb scissors 5 blade',
        'bag sealer mini',
        'dish drying mat',
        'egg timer indicator',
        'cherry pitter tool',
        'citrus juicer hand',
        'dough scraper bench',
        'salad spinner bowl',
        'jar opener under cabinet',
        'corn cob stripper',
      ],
    },
    {
      id: 'car',
      displayName: 'Car Accessories',
      hebrewLabel: 'רכב',
      emoji: '🚗',
      description: 'אביזרי נסיעה, ארגון, בטיחות ונוחות לרכב',
      weight: 10,
      enabled: true,
      keywords: [
        'portable tire inflator',
        'car vacuum cleaner wireless',
        'car phone holder magnetic',
        'Bluetooth FM transmitter car',
        'obd2 scanner diagnostic tool',
        'car organizer between seats',
        'car trash can bin',
        'blind spot mirrors car',
        'windshield sun shade umbrella',
        'trunk organizer foldable',
        'seat gap filler organizer',
        'car seat hook hanger',
        'headrest tablet holder',
        'steering wheel lock heavy duty',
        'car air freshener solar',
        'license plate backup camera',
        'scratch repair pen car',
        'dash cam front and rear',
        'jump starter power bank',
        'car door edge protector',
      ],
    },
    {
      id: 'home',
      displayName: 'Home Decor & Utility',
      hebrewLabel: 'בית',
      emoji: '🏡',
      description: 'פתרונות שימושיים לשיפור הבית, בידוד ועיצוב קל',
      weight: 9,
      enabled: true,
      keywords: [
        'door draft stopper',
        'digital hygrometer thermometer',
        'key bowl for entry table',
        'felt furniture pads',
        'wall mount mail organizer',
        'door handle bumper protector',
        'window insulation film',
        'essential oil diffuser ultrasonic',
        'magnetic screen door mesh',
        'decorative wall hooks',
        'carpet tape double sided',
        'outlet cover box safety',
        'photo frame collage wall',
        'step stool folding',
        'window blind duster',
        'remote control holder wall',
        'table corner protector baby',
        'draft guard window',
        'leather repair patch adhesive',
        'door stop wedge rubber',
      ],
    },
    {
      id: 'cleaning',
      displayName: 'Cleaning Tools',
      hebrewLabel: 'ניקיון',
      emoji: '🧹',
      description: 'מברשות וכלים לניקיון מהיר ויעיל של הבית והמשרד',
      weight: 8,
      enabled: true,
      keywords: [
        'telescopic cleaning brush',
        'window squeegee cleaner',
        'microfiber duster extendable',
        'keyboard cleaning gel',
        'pet hair remover roller',
        'bottle cleaning brush set',
        'pumice stone toilet bowl cleaner',
        'drill brush attachment set',
        'mini desktop vacuum cleaner',
        'lint shaver fabric defuzzer',
        'drain clog remover tool',
        'screen cleaner spray cloth',
        'blind cleaner tool',
        'groove cleaning brush window',
        'sponge holder kitchen sink',
        'stove gap covers silicone',
        'washing machine cleaner tablets',
        'micro fiber cleaning cloths',
        'shoe cleaner cream',
        'pot pan scraper tool',
      ],
    },
    {
      id: 'organization',
      displayName: 'Home Organization',
      hebrewLabel: 'ארגון',
      emoji: '📦',
      description: 'פתרונות אחסון וסידור ארונות, מגירות ומדפים',
      weight: 8,
      enabled: true,
      keywords: [
        'under sink organizer sliding',
        'cable clip organizer silicone',
        'makeup brush holder organizer',
        'drawer dividers adjustable',
        'remote control organizer holder',
        'refrigerator magnet spice rack',
        'purse organizer insert',
        'belt hanger rack closet',
        'hat rack hanger hooks',
        'jewelry organizer box travel',
        'egg holder for refrigerator',
        'mop and broom holder wall',
        'lazy susan turntable organizer',
        'water bottle organizer rack',
        'socks underwear organizer divider',
        'cord wrapper for kitchen appliances',
        'bedside caddy organizer bag',
        'key holder wall mount decorative',
        'desk organizer pen holder',
        'foil and plastic wrap organizer',
      ],
    },
    {
      id: 'diy',
      displayName: 'DIY & Crafting',
      hebrewLabel: 'עשה זאת בעצמך',
      emoji: '🛠️',
      description: 'מדידה, תיקון קל, הדבקה ועבודות יצירה ביתיות',
      weight: 7,
      enabled: true,
      keywords: [
        'contour gauge duplicator',
        'magnetic wristband for screws',
        'laser level line tool',
        'hot glue gun cordless',
        'thread locker glue blue',
        'tape measure digital',
        'wire stripper cutter auto',
        'silicone sealant tool kit',
        'screw extractor set damaged',
        'hand drill pin vise',
        'utility knife folding utility',
        'drywall patch repair kit',
        'precision tweezers set antistatic',
        'plastic welder staple gun',
        'caliper digital stainless steel',
        'corner clamp 90 degree',
        'super glue adhesive gel',
        'sanding blocks sponge',
        'glass cutter tool wheel',
        'rotary tool kit mini',
      ],
    },
    {
      id: 'travel',
      displayName: 'Travel Accessories',
      hebrewLabel: 'טיולים',
      emoji: '✈️',
      description: 'אריזה, בטיחות, ונוחות במהלך טיסות ונסיעות בחו"ל',
      weight: 8,
      enabled: true,
      keywords: [
        'packing cubes travel compression',
        'travel bottle set silicone',
        'luggage scale digital portable',
        'neck pillow memory foam travel',
        'passport holder wallet RFID',
        'travel adapter universal plug',
        'luggage tag leather privacy',
        'shoe bags travel storage',
        'portable pill organizer travel',
        'quick dry microfiber towel',
        'TSA approved luggage locks',
        'compact umbrella windproof travel',
        'travel laundry bag dirty',
        'cup holder for luggage suitcase',
        'security door lock portable',
        'toothbrush travel case capsule',
        'belt bag travel fanny pack',
        'tech organizer travel case',
        'sleeping eye mask contoured',
        'foldable duffle bag travel',
      ],
    },
    {
      id: 'camping',
      displayName: 'Camping Gear',
      hebrewLabel: 'קמפינג',
      emoji: '🏕️',
      description: 'ציוד שטח, בישול חוץ, תאורה והישרדות בשטח',
      weight: 8,
      enabled: true,
      keywords: [
        'camping lantern rechargeable',
        'fire starter flint steel',
        'paracord bracelet survival tool',
        'collapsible water bucket',
        'camping folding bucket',
        'emergency sleeping bag thermal',
        'collapsible pocket bellows',
        'portable camping shower water',
        'camping cup stainless steel',
        'sleeping pad camping inflatable',
        'hammock double tree straps',
        'compass survival pocket',
        'camping pillow inflatable',
        'camping micro pillow',
        'solar charger power bank waterproof',
        'mosquito head net mesh',
        'camping stove wind screen',
        'collapsible cooking pot silicone',
        'tent stakes heavy duty peg',
        'waterproof dry bag backpack',
      ],
    },
    {
      id: 'pets',
      displayName: 'Pet Accessories',
      hebrewLabel: 'חיות מחמד',
      emoji: '🐶',
      description: 'אביזרים לטיפוח, האכלה, משחק ונוחות לכלבים וחתולים',
      weight: 6,
      enabled: true,
      keywords: [
        'dog water bottle portable',
        'pet grooming glove brush',
        'cat self groomer wall brush',
        'dog nail grinder electric',
        'cat laser toy automatic',
        'slow feeder dog bowl',
        'pet hair remover brush car',
        'dog leash double two handle',
        'cat window perch hammock',
        'dog grooming scissors kit',
        'collapsible dog bowls travel',
        'dog treat pouch training bag',
        'pet feeding mat silicone',
        'dog seat belt harness car',
        'cat scratching post sisal',
        'pet collar light LED',
        'cat litter scoop holder',
        'tick remover tool set',
        'dog toothbrush toy rubber',
        'pet hair dryer stand',
      ],
    },
    {
      id: 'phone',
      displayName: 'Phone Gadgets',
      hebrewLabel: 'טלפון',
      emoji: '📱',
      description: 'מעמדים, כבלי טעינה, ואביזרים קטנים לסמארטפון',
      weight: 7,
      enabled: true,
      keywords: [
        'magnetic phone stand desk',
        'ring light with stand desktop',
        'phone charm strap beaded',
        'cell phone lanyard wrist strap',
        'privacy screen protector glass',
        'phone cleaner kit port',
        'universal phone mount tripod',
        'wireless charging station dock',
        'phone screen magnifier projector',
        'phone wallet sleeve stick on',
        'waterproof phone pouch bag',
        'phone cooler fan radiator',
        'magnetic plate sticker phone',
        'phone stand fold laptop',
        'car vents phone mount gravity',
        'phone lens kit macro fish',
        'table phone holder flexible arm',
        'wireless selfie stick tripod',
        'cell phone stand table holder',
        'phone charging cable fast magnetic',
      ],
    },
    {
      id: 'computer',
      displayName: 'Computer Accessories',
      hebrewLabel: 'מחשב',
      emoji: '💻',
      description: 'מעמדים, ניקוי, תאורה, ואביזרים שימושיים ללפטופ ומחשב שולחני',
      weight: 6,
      enabled: true,
      keywords: [
        'keyboard cleaning brush kit',
        'monitor light bar screenbar',
        'laptop stand aluminum adjustable',
        'mouse pad wrist rest ergonomic',
        'USB hub multiport adapter USB',
        'web camera cover slide',
        'laptop sleeve bag shockproof',
        'trackball mouse ergonomic wireless',
        'head phone hanger under desk',
        'external SSD hard drive enclosure',
        'USB desk fan quiet',
        'mini microphone PC laptop',
        'thermal paste syringe CPU',
        'keyboard wrist rest memory foam',
        'USB light light flexible computer',
        'laptop cooling pad stand',
        'dust plugs laptop computer',
        'monitor mount stand arm',
        'wireless presenter pointer remote',
        'keycap puller key extraction tool',
      ],
    },
    {
      id: 'office',
      displayName: 'Office Supplies',
      hebrewLabel: 'משרד',
      emoji: '💼',
      description: 'נוחות עבודה, ארגון שולחן כתיבה, וכלי כתיבה שימושיים',
      weight: 6,
      enabled: true,
      keywords: [
        'desk organizer document holder',
        'paper cutter paper trimmer',
        'cable sleeve zipper management',
        'seat cushion orthopedic memory',
        'desk pad mat large leather',
        'dry erase whiteboard magnetic',
        'foot rest under desk office',
        'notebook journal leather writing',
        'push pin clips wood pegs',
        'pen organizer desktop holder',
        'correction tape dispenser roller',
        'book stand holder adjustable',
        'document scanner bag travel',
        'privacy stamp roller cover',
        'stapler remover set office',
        'badge reel holder retractable ID',
        'file folder expanding letter',
        'tape dispenser desk holder',
        'desk drawer organizer tray drawer',
        'gel pens set black blue',
      ],
    },
    {
      id: 'lighting',
      displayName: 'Utility Lighting',
      hebrewLabel: 'תאורה',
      emoji: '💡',
      description: 'תאורת חיישנים, מנורות קריאה, ותאורת אווירה לבית ולשטח',
      weight: 9,
      enabled: true,
      keywords: [
        'motion sensor light strip closet',
        'under cabinet light rechargeable',
        'night light plug in sensor',
        'book light clip on rechargeable',
        'sunset lamp projector light',
        'flame light bulb LED fire',
        'camping flashlight zoomable zoom',
        'fairy lights battery operated LED',
        'toilet bowl night light motion',
        'desk lamp cordless rechargeable',
        'cabinet hinge light LED utility',
        'motion sensor night light wall',
        'projection clock ceiling projector',
        'smart light bulb adapter wifi',
        'solar deck lights outdoor fence',
        'candle warmer lamp top heater',
        'starlight projector galaxy laser',
        'flexible strip light neon sign',
        'mini flashlight keychain USB rechargeable',
        'step light indoor motion wall',
      ],
    },
    {
      id: 'garden',
      displayName: 'Garden Tools',
      hebrewLabel: 'גינה',
      emoji: '🪴',
      description: 'השקיה אוטומטית, תמיכה בצמחים, ותאורה דקורטיבית לגינה',
      weight: 8,
      enabled: true,
      keywords: [
        'solar motion light outdoor garden',
        'plant watering spikes self water',
        'garden grafting tool scissors kit',
        'drip irrigation kit system garden',
        'solar fountain pump water bird',
        'plant support clips trellis garden',
        'soil moisture meter sensor meter',
        'grow light strip USB timer',
        'seed starter trays humidity dome',
        'garden kneeler pad cushion foam',
        'bird feeder hanger window bird',
        'garden hose nozzle spray high',
        'hanging planter basket hook chain',
        'solar firefly lights garden pathway',
        'plant root growing box grafting',
        'branch cutter garden shear trimmer',
        'solar ground lights disc lights',
        'plant tags labels markers garden',
        'bug zapper solar lamp garden',
        'plant ties velcro soft roll',
      ],
    },
    {
      id: 'bathroom',
      displayName: 'Bathroom Utility',
      hebrewLabel: 'אמבטיה',
      emoji: '🛁',
      description: 'פתרונות לכיור, ניקוז, מעמדי מברשות ונוחות רחצה',
      weight: 7,
      enabled: true,
      keywords: [
        'silicone sink faucet splash guard',
        'toilet brush silicone holder soft',
        'toothpaste squeegee roller wall mount',
        'bath pillow bathtub neck head',
        'hair catcher shower drain protector',
        'bathroom mirror anti fog spray',
        'razor holder wall mount hook',
        'toothbrush holder wall mount electric',
        'soap dispenser wall mount manual',
        'shower head high pressure water',
        'toilet seat lifter handle toilet',
        'bathtub mat non slip suction',
        'toilet paper holder shelf phone',
        'vanity mirror lights LED strip',
        'shower squeegee glass door cleaner',
        'soap saver pad soap dish',
        'bathroom shelf adhesive corner shower',
        'hair dryer holder wall mount',
        'toilet bowl deodorizer gel stamp',
        'waterproof phone box bathroom wall',
      ],
    },
    {
      id: 'laundry',
      displayName: 'Laundry Helpers',
      hebrewLabel: 'כביסה',
      emoji: '🧺',
      description: 'שקיות כביסה, קיפול בגדים, ייבוש וגיהוץ קל',
      weight: 7,
      enabled: true,
      keywords: [
        'mesh laundry bags underwear bra',
        'wool dryer balls natural softener',
        'collapsible laundry basket space save',
        'lint remover clothes fuzz shaver',
        'socks hanger multi clip drying',
        'clothes folding board shirt flip',
        'laundry detergent sheet dispenser',
        'clothes drying rack sock hanger',
        'laundry beads cup storage bottle',
        'ironing mat pad heat resistant',
        'hanging laundry hamper door bag',
        'washing machine feet pad anti',
        'lint trap net washing machine',
        'shoe washing mesh bag laundry',
        'clothes line portable travel clothes',
        'fabric steamer portable travel iron',
        'clothespins pegs wooden plastic clamp',
        'hanger space saving magic hanger',
        'lint roller set adhesive sheet',
        'washer lint remover floating ball',
      ],
    },
    {
      id: 'coffee',
      displayName: 'Coffee Gadgets',
      hebrewLabel: 'קפה',
      emoji: '☕',
      description: 'אביזרים להכנה, הקצפה, טחינה ועיצוב כוסות קפה',
      weight: 6,
      enabled: true,
      keywords: [
        'coffee frother electric mixer',
        'coffee grinder manual hand crank',
        'pour over coffee dripper cup',
        'coffee scale timer digital kitchen',
        'coffee tamper espresso powder hammer',
        'coffee distributor leveler tool espresso',
        'reusable coffee capsule pod cup',
        'coffee syphon maker glass syphon',
        'coffee bag spoon clip',
        'milk frothing pitcher stainless jug',
        'espresso dosing ring magnetic funnel',
        'coffee filter holder rack wood',
        'cup warmer mug heater coaster',
        'coffee stencil art template cake',
        'espresso puck screen reuse metal',
        'manual milk frother hand pump',
        'coffee mug travel vacuum double',
        'cold brew coffee maker bottle',
        'espresso cleaning brush grinder cleaning',
        'coffee syrup dispenser bottle pump',
      ],
    },
    {
      id: 'baby',
      displayName: 'Baby Safety & Care',
      hebrewLabel: 'תינוקות',
      emoji: '👶',
      description: 'מגני בטיחות, אביזרים לעגלה, וטיפוח עדין לתינוקות',
      weight: 5,
      enabled: true,
      keywords: [
        'baby corner protector table guard',
        'cabinet locks child safety strap',
        'silicone baby bib pocket bib',
        'pacifier clip holder leash silicone',
        'baby knee pads crawling helper',
        'baby nasal aspirator hand bulb',
        'baby bath thermometer floating toy',
        'stroller organizer bag drink holder',
        'baby bottle drying rack space',
        'car window shades baby protection',
        'baby finger toothbrush soft silicone',
        'baby food grinder masher bowl',
        'stroller hook hangers aluminum carabiner',
        'baby bath visor cap ears',
        'pacifier box travel case container',
        'baby safety harness walking helper',
        'outlet plugs childproof cover wall',
        'baby food storage container silicone',
        'baby nail trimmer electric file',
        'baby head protection pad backpack',
      ],
    },
    {
      id: 'kids',
      displayName: 'Kids Toys & Activity',
      hebrewLabel: 'ילדים',
      emoji: '🧸',
      description: 'צעצועי התפתחות, לוחות כתיבה דיגיטליים, ויצירה לילדים',
      weight: 5,
      enabled: true,
      keywords: [
        'magnetic drawing board sketch pad',
        'LCD writing tablet digital board',
        'wooden pattern blocks puzzle',
        'balance stepping stones kids balance',
        'wooden tangram puzzle brain teaser',
        'coloring roll paper wall sticky',
        'coin bank counter digital piggy',
        'rocket launcher toy air pressure',
        'kids binoculars outdoor explorer kit',
        'play tent foldable kids pop',
        'diamond painting stickers kits kids',
        'bath toys organizer mesh bag',
        'toddler cleaning set mini broom',
        'water drawing book magic water',
        'projection torch flashlight projector toy',
        'bubble machine gun electric bubble',
        'clay modeling set air dry',
        'child height ruler wall hanging',
        'kids watch analog teaching learning',
        'paper airplane launcher folding toy',
      ],
    },
    {
      id: 'fitness',
      displayName: 'Fitness Accessories',
      hebrewLabel: 'כושר',
      emoji: '🏋️',
      description: 'גומיות התנגדות, מדי ספורט, עיסוי שרירים ואימון Core',
      weight: 5,
      enabled: true,
      keywords: [
        'resistance bands elastic loop exercise',
        'ab roller wheel abdominal core',
        'jump rope digital counter speed',
        'grip strength trainer hand squeezer',
        'yoga mat strap carrier bag',
        'muscle roller massage stick roller',
        'fitness tracker smart bracelet sleep',
        'water bottle time marker leakproof',
        'cooling towel quick dry sports',
        'push up board stand',
        'ankle straps cable machine attachment',
        'running belt bag phone holder',
        'barbell pad squat shoulder cushion',
        'dual exercise sliders gym core',
        'kinesiology tape sports tape muscle',
        'wrist wraps gym weight lifting',
        'sweat wristbands headbands set sports',
        'liquid chalk bottle gym weight',
        'pilates ring dual grip circle',
        'exercise ball hand pump balance',
      ],
    },
    {
      id: 'bicycle',
      displayName: 'Bicycle Gear',
      hebrewLabel: 'אופניים',
      emoji: '🚲',
      description: 'מעמדים לנייד, פנסי USB, מגני בוץ ונוחות רכיבה',
      weight: 5,
      enabled: true,
      keywords: [
        'bicycle phone mount handlebar holder',
        'bike light USB rechargeable head',
        'bike saddle cushion gel seat',
        'bicycle lock chain combination lock',
        'bike tire pump portable mini',
        'cycling gloves gel finger gloves',
        'bike bag frame tube bag',
        'bicycle water bottle cage holder',
        'bike mirror handlebar rearview mirror',
        'bike tool kit multitool wrench',
        'cycling sunglasses polarized sports glasses',
        'bicycle bell ring loud brass',
        'bike wall mount rack wall',
        'bicycle fender guard mud guard',
        'spoke lights wheel lights LED',
        'bike chain lube clean dry',
        'cycling leg warmers compression sleeve',
        'bike repair stand clamp stand',
        'bicycle seat bag saddle wedge',
        'valve adapter converter presta schrader',
      ],
    },
    {
      id: 'bbq',
      displayName: 'BBQ Utilities',
      hebrewLabel: 'על האש',
      emoji: '🍖',
      description: 'מברשות ניקוי, מדי טמפרטורה, מגנטים לגריל ונוחות צלייה',
      weight: 6,
      enabled: true,
      keywords: [
        'meat claws shredder pulled pork',
        'grill brush scraper stainless wire',
        'bbq meat thermometer instant read',
        'grill mat non stick mesh',
        'silicone basting brush oil brush',
        'burger press hamburger patty maker',
        'bbq gloves heat resistant kitchen',
        'skewer sticks metal barbecue needles',
        'charcoal fire starter chimney charcoal',
        'grill lights magnet magnetic base',
        'grill cover waterproof heavy duty',
        'bbq kabob grilling baskets steel',
        'grill tongs locking kitchen tongs',
        'bbq smoker box wood chips',
        'salt pepper grinder wood mill',
        'spray bottle for barbecue oil',
        'corn on cob holders metal',
        'bbq apron canvas utility apron',
        'skewers rack barbecue frame stand',
        'bbq cleaning brick block stone',
      ],
    },
    {
      id: 'storage',
      displayName: 'Home Storage',
      hebrewLabel: 'אחסון',
      emoji: '🗃️',
      description: 'קופסאות אחסון שקופות, שקיות ואקום, וארגוניות נעליים',
      weight: 8,
      enabled: true,
      keywords: [
        'vacuum storage bags space saving',
        'shoe storage box clear stackable',
        'storage organizer bins drawer organizer',
        'cosmetic display stand storage drawer',
        'hat organizer hangers clip hooks',
        'magnetic key holder cloud wall',
        'tea bag organizer chest box',
        'battery storage organizer case tester',
        'file folder storage box desktop',
        'tissue box holder storage compartment',
        'storage box under bed folding',
        'cable storage box wire management',
        'pill organizer box travel weekly',
        'pen organizer holder storage desk',
        'jewelry roll organizer bag fold',
        'canvas storage basket toy bin',
        'coin holder case storage bank',
        'knife organizer drawer insert tray',
        'cup drying rack counter drainer',
        'blanket storage bag zipper bag',
      ],
    },
    {
      id: 'electronics',
      displayName: 'Electronics Gadgets',
      hebrewLabel: 'אלקטרוניקה',
      emoji: '🔌',
      description: 'מודדים דיגיטליים, מלחמים, מאזניים קטנים וכלי בדיקה ביתיים',
      weight: 7,
      enabled: true,
      keywords: [
        'magnetic cable organizer clip desktop',
        'digital multimeter electrical tester pen',
        'precision tweezers pack',
        'magnifying glass hand loupe lens',
        'digital voice recorder dictaphone record',
        'USB adapter converter type c',
        'wire tracker network cable tester',
        'mini scale jewelry pocket digital',
        'portable laser distance meter rangefinder',
        'electronic scale kitchen luggage weight',
        'wire connector term block solder',
        'heat shrink tubing electrical wire',
        'led tester detector backlight tester',
        'audio extractor splitter optical audio',
        'bluetooth audio adapter receiver jack',
        'mini stereo amplifier board audio',
        'electronic organizer bag cable travel',
        'battery capacity tester indicator power',
        'digital microscope screen camera zoom',
        'voltage test pen non contact',
      ],
    },
    {
      id: 'smarthome',
      displayName: 'Smart Home Controls',
      hebrewLabel: 'בית חכם',
      emoji: '🎛️',
      description: 'שקעי wifi, חיישני טמפרטורה, ומתגים דיגיטליים',
      weight: 7,
      enabled: true,
      keywords: [
        'smart plug socket wifi plug',
        'smart switch button pusher remote',
        'IR remote control smart hub',
        'smart temperature humidity sensor zigbee',
        'smart light switch wall panel',
        'smart bulb holder wifi adapter',
        'window sensor alarm wifi door',
        'smart water leak detector alarm',
        'motion sensor alarm wifi battery',
        'smart door lock card keyless',
        'smart finger bot switch bot',
        'wifi signal repeater range extender',
        'smart led controller wifi dimmer',
        'smart gas leak alarm gas',
        'smart radiator valve thermostat zigbee',
        'smart curtain motor automatic curtain',
        'wifi garage door opener remote',
        'smart siren alarm wifi sounder',
        'zigbee gateway hub wireless bridge',
        'smart air quality monitor co2',
      ],
    },
    {
      id: 'emergency',
      displayName: 'Emergency & Safety',
      hebrewLabel: 'חירום',
      emoji: '🚨',
      description: 'רדיו סולארי, שמיכות מילוט, פנסי ראש וכלי הצלה לרכב ולבית',
      weight: 6,
      enabled: true,
      keywords: [
        'emergency survival kit bag gear',
        'hand crank radio solar emergency',
        'tactical pen glass breaker weapon',
        'emergency whistle rescue loud whistle',
        'space blanket emergency thermal foil',
        'emergency ponchos rain coat gear',
        'high visibility safety vest',
        'window breaker seatbelt cutter tool',
        'emergency water filter straw survival',
        'portable chain saw wire pocket',
        'tourniquet band emergency medical belt',
        'led headlamp flashlight head lamp',
        'glow sticks emergency lights chemical',
        'multi tool pliers pocket multitool',
        'fire emergency blanket glass fiber',
        'waterproof matches container match stick',
        'first aid kit bag empty',
        'hand hand warmers reusable pocket',
        'solar lighter outdoor fire starter',
        'emergency warning triangle red folding',
      ],
    },
    {
      id: 'security',
      displayName: 'Home Security',
      hebrewLabel: 'אבטחה',
      emoji: '🔒',
      description: 'קופסאות מפתח, מנעולי דלת ניידים, ומעקבי Bluetooth',
      weight: 6,
      enabled: true,
      keywords: [
        'key lock box wall mount',
        'portable door lock travel lock',
        'door stop alarm sensor alert',
        'rf detector anti spy camera',
        'window security locks safety sliding',
        'smart key lock padlock fingerprint',
        'simulated security camera dummy cam',
        'personal alarm keychain safe sound',
        'key finder bluetooth locator tracker',
        'rfid blocking card sleeves protection',
        'security lock cable steel cable',
        'combination padlock luggage lock number',
        'home lock box keys wall',
        'door reinforcement lock secure latch',
        'magnetic window sensors alarm sounder',
        'warning stickers security alarm sign',
        'biometric cabinet lock drawer file',
        'hidden wall socket safe box',
        'book safe combination dictionary safe',
        'security door stop bar bracket',
      ],
    },
    {
      id: 'photography',
      displayName: 'Photography Accessories',
      hebrewLabel: 'צילום',
      emoji: '📷',
      description: 'מעמדי חצובה, תאורת רינג, וציוד ניקוי עדשות',
      weight: 4,
      enabled: true,
      keywords: [
        'mini light box photo studio',
        'photo background paper studio backdrop',
        'lens cleaning kit pen air',
        'universal diffuser softbox flash reflector',
        'camera wrist strap paracord neck',
        'desk mount camera stand pole',
        'camera tripod mount phone mount',
        'lens filter case pouch wallet',
        'green screen background chroma key',
        'ring light phone selfie clip',
        'memory card case waterproof box',
        'step up ring filter step adapter',
        'mini tripod stand tabletop desktop',
        'bounce card flash diffuser card',
        'camera rain cover waterproof coat',
        'battery case holder aa aaa',
        'hot shoe bubble level spirit',
        'camera mount holder clip clamp',
        'softbox lighting kit mini studio',
        'lens hood cover sun shade',
      ],
    },
    {
      id: 'tools',
      displayName: 'Hand Tools',
      hebrewLabel: 'כלים',
      emoji: '🔧',
      description: 'מברגים מגנטיים, גלאי מתכות לקיר, ומחלצי ברגים פגומים',
      weight: 7,
      enabled: true,
      keywords: [
        'magnetic screwdriver set precision kits',
        'universal socket wrench multi tool',
        'digital pocket scale gram scale',
        'stud finder wall scanner detector',
        'magnetic pickup tool telescoping stick',
        'step drill bit wood drilling',
        'deburring tool hand debur scraper',
        'flexible extension drill bit hose',
        'thread pitch gauge metric screw',
        'center punch automatic spring loaded',
        'tap and die set screw',
        'wire twist tool drill driver',
        'automatic wire stripper crimper plier',
        'socket adapter impact driver hex',
        'magnetic screwdriver ring magnetizer ring',
        'hand riveter gun rivet tool',
        'pocket hole jig kit joinery',
        'right angle drill adapter hex',
        'level tool pocket level bubble',
        'hex key wrench set allen',
      ],
    },
    {
      id: 'car_care',
      displayName: 'Car Care & Polish',
      hebrewLabel: 'טיפוח הרכב',
      emoji: '🧽',
      description: 'מטליות ייבוש, ערכות פוליש וטיפוח פנים וחוץ הרכב',
      weight: 8,
      enabled: true,
      keywords: [
        'microfiber car drying towel towel',
        'car washing mitt chenille glove',
        'windshield glass water repellent spray',
        'clay bar car detailing clean',
        'wheel rim cleaning brush wire',
        'scratch repair cloth wax compound',
        'leather cleaner conditioner cream seat',
        'foam lance soap bottle spray',
        'micro fiber wax applicator pads',
        'car cleaning brush vent detailing',
        'car wash squeeze sprayer pump',
        'car windshield repair kit crack',
        'headlight restoration kit polish clean',
        'plastic trim restorer agent polish',
        'car interior cleaning gel slime',
        'buffing pads drill polishing pad',
        'rain repellent windshield wiper treatment',
        'car dust duster static brush',
        'tire valve cap metal tire',
        'wash bucket dirt trap filter',
      ],
    },
  ],
};

export const discoveryConfig: DiscoveryConfig = {
  strategies: legacyDiscoveryStrategies,
  categories: discoveryLibraryV2.categories,
};
