import { DiscoveryConfig, DiscoveryConfigV2, DiscoveryStrategy } from './discovery-types';

/**
 * Legacy V1 strategies used by the active scheduler.
 * This preserves 100% backward compatibility and isolates development of V2.
 */
export const legacyDiscoveryStrategies: DiscoveryStrategy[] = [
  { type: 'keyword', keyword: 'vegetable chopper', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'sink organizer', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'car phone holder', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'car vacuum cleaner', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'motion sensor light', pages: 1, pageSize: 20 },
  { type: 'keyword', keyword: 'smart plug', pages: 1, pageSize: 20 },
];

/**
 * Editorial V2.1 Category Library.
 * Contains 30 categories with variable counts of unique, safe keywords (507 total).
 */
export const discoveryLibraryV2: DiscoveryConfigV2 = {
  categoriesPerRun: 3,
  defaultKeywordsPerCategory: 1,
  categories: [
    {
      id: 'kitchen',
      displayName: 'Kitchen Gadgets',
      hebrewLabel: 'מטבח',
      emoji: '🍳',
      description: 'שימושי למטבח הביתי, הכנת אוכל, בישול ואפייה',
      weight: 10,
      enabled: true,
      keywords: [
        'vegetable chopper',
        'oil spray dispenser for cooking',
        'garlic press rocker stainless steel',
        'cooking utensils set silicone',
        'magnetic kitchen timer',
        'digital kitchen scale precision',
        'knife sharpener 3 stage manual',
        'instant read meat thermometer digital',
        'milk frother handheld electric',
        'silicone baking mat',
        'herb scissors 5 blade',
        'mini heat bag sealer rechargeable',
        'dish drying mat',
        'egg timer indicator',
        'cherry pitter tool',
        'lemon squeezer hand press',
        'dough scraper bench',
        'salad spinner bowl',
        'jar opener under cabinet',
        'corn cob stripper',
        'automatic pan stirrer timer',
        'electric wine opener set rechargeable',
        'electric pepper grinder gravity',
        'dumpling maker press mold',
        'microwave cleaner steam angry mama'
      ],
    },
    {
      id: 'car',
      displayName: 'Car Accessories',
      hebrewLabel: 'רכב',
      emoji: '🚗',
      description: 'אביזרי נסיעה, ארגון, בטיחות ונוחות לרכב',
      weight: 10,
      enabled: true,
      keywords: [
        'digital portable tire inflator cordless',
        'wireless car vacuum cleaner handheld',
        'car phone holder magnetic dashboard',
        'car bluetooth fm transmitter usb',
        'obd2 scanner diagnostic tool',
        'seat gap filler organizer pocket',
        'car trash can bin',
        'blind spot mirror adjustable car',
        'car windshield sun shade umbrella',
        'foldable trunk organizer bags',
        'car seat headrest hook hanger',
        'car headrest tablet holder mount',
        'steering wheel lock heavy duty',
        'solar rotating car air freshener',
        'license plate backup camera',
        'dash cam front rear camera',
        'car jump starter power bank',
        'car door edge protector strip',
        'seat back organizer storage',
        'car windshield repair kit',
        'tire pressure gauge digital',
        'car key fob signal blocker bag',
        'car neck pillow memory foam',
        'car windshield cleaning brush tool',
        'car cup holder expander adapter'
      ],
    },
    {
      id: 'home',
      displayName: 'Home Decor & Utility',
      hebrewLabel: 'בית',
      emoji: '🏡',
      description: 'פתרונות שימושיים לשיפור הבית, בידוד ועיצוב קל',
      weight: 9,
      enabled: true,
      keywords: [
        'door draft stopper',
        'digital hygrometer thermometer',
        'key bowl for entry table',
        'felt furniture pads',
        'wall mount mail organizer',
        'door handle bumper protector',
        'window insulation film',
        'essential oil diffuser ultrasonic',
        'magnetic screen door mesh',
        'decorative wall hooks',
        'carpet tape double sided',
        'outlet cover box safety',
        'photo frame collage wall',
        'step stool folding',
        'window blind duster',
        'remote control holder wall',
        'table corner protector baby',
        'draft guard window',
        'leather repair patch adhesive',
        'door stop wedge rubber',
        'magnetic key holder cloud wall',
        'under door draft stopper double'
      ],
    },
    {
      id: 'cleaning',
      displayName: 'Cleaning Tools',
      hebrewLabel: 'ניקיון',
      emoji: '🧹',
      description: 'מברשות וכלים לניקיון מהיר ויעיל של הבית והמשרד',
      weight: 8,
      enabled: true,
      keywords: [
        'telescopic cleaning brush',
        'window squeegee cleaner',
        'microfiber duster extendable',
        'keyboard cleaning gel',
        'pet hair remover roller',
        'bottle cleaning brush set',
        'pumice stone toilet bowl cleaner',
        'drill brush attachment set',
        'mini desktop vacuum cleaner',
        'lint shaver fabric defuzzer',
        'drain clog remover tool',
        'screen cleaner spray cloth',
        'blind cleaner tool',
        'groove cleaning brush window',
        'sponge holder kitchen sink',
        'stove gap covers silicone',
        'washing machine cleaner tablets',
        'reusable pet hair remover roller',
        'pot pan scraper tool',
        'electric spin scrubber cordless'
      ],
    },
    {
      id: 'organization',
      displayName: 'Home Organization',
      hebrewLabel: 'ארגון',
      emoji: '📦',
      description: 'פתרונות אחסון וסידור ארונות, מגירות ומדפים',
      weight: 8,
      enabled: true,
      keywords: [
        'under sink sliding organizer pull out',
        'silicone cable clip organizer self adhesive',
        'makeup brush holder organizer',
        'drawer dividers adjustable',
        'remote control organizer holder',
        'refrigerator magnet spice rack',
        'purse organizer insert',
        'belt hanger rack closet',
        'hat rack hanger hooks',
        'jewelry organizer box travel',
        'egg holder for refrigerator',
        'mop and broom holder wall',
        'lazy susan turntable organizer',
        'water bottle organizer rack',
        'socks underwear organizer divider',
        'cord wrapper for kitchen appliances',
        'bedside caddy organizer bag',
        'key holder wall mount decorative',
        'desk organizer pen holder',
        'foil and plastic wrap organizer',
        'magnetic remote control holder wall',
        'shoe slot organizer space saver'
      ],
    },
    {
      id: 'diy',
      displayName: 'DIY & Crafting',
      hebrewLabel: 'עשה זאת בעצמך',
      emoji: '🛠️',
      description: 'מדידה, תיקון קל, הדבקה ועבודות יצירה ביתיות',
      weight: 7,
      enabled: true,
      keywords: [
        'contour gauge duplicator',
        'magnetic wristband for screws',
        'laser level line tool',
        'hot glue gun cordless',
        'tape measure digital',
        'wire stripper cutter auto',
        'silicone sealant tool kit',
        'screw extractor set damaged',
        'hand drill pin vise',
        'plastic welder staple gun',
        'caliper digital stainless steel',
        'corner clamp 90 degree',
        'glass cutter tool wheel',
        'rotary tool kit mini',
        'multitool pocket knife folding'
      ],
    },
    {
      id: 'travel',
      displayName: 'Travel Accessories',
      hebrewLabel: 'טיולים',
      emoji: '✈️',
      description: 'אריזה, בטיחות, ונוחות במהלך טיסות ונסיעות בחו"ל',
      weight: 8,
      enabled: true,
      keywords: [
        'packing cubes travel compression',
        'travel bottle set silicone',
        'luggage scale digital portable',
        'neck pillow memory foam travel',
        'passport holder wallet RFID',
        'travel adapter universal plug',
        'luggage tag leather privacy',
        'shoe bags travel storage',
        'portable pill organizer travel',
        'quick dry microfiber towel',
        'TSA approved luggage locks',
        'compact umbrella windproof travel',
        'travel laundry bag dirty',
        'cup holder for luggage suitcase',
        'security door lock portable',
        'toothbrush travel case capsule',
        'belt bag travel fanny pack',
        'tech organizer travel case',
        'sleeping eye mask contoured',
        'foldable duffle bag travel'
      ],
    },
    {
      id: 'camping',
      displayName: 'Camping Gear',
      hebrewLabel: 'קמפינג',
      emoji: '🏕️',
      description: 'ציוד שטח, בישול חוץ, תאורה והישרדות בשטח',
      weight: 8,
      enabled: true,
      keywords: [
        'camping lantern rechargeable',
        'fire starter flint steel',
        'paracord bracelet survival tool',
        'collapsible water bucket',
        'camping folding bucket',
        'emergency sleeping bag thermal',
        'collapsible pocket bellows',
        'portable camping shower water',
        'camping cup stainless steel',
        'sleeping pad camping inflatable',
        'hammock double tree straps',
        'compass survival pocket',
        'camping pillow inflatable',
        'solar charger power bank waterproof',
        'mosquito head net mesh',
        'camping stove wind screen',
        'collapsible cooking pot silicone',
        'tent stakes heavy duty peg'
      ],
    },
    {
      id: 'pets',
      displayName: 'Pet Accessories',
      hebrewLabel: 'חיות מחמד',
      emoji: '🐶',
      description: 'אביזרים לטיפוח, האכלה, משחק ונוחות לכלבים וחתולים',
      weight: 6,
      enabled: true,
      keywords: [
        'dog water bottle portable',
        'pet grooming glove brush',
        'cat self groomer wall brush',
        'dog nail grinder electric',
        'cat laser toy automatic',
        'slow feeder dog bowl',
        'pet hair remover brush car',
        'dog leash double two handle',
        'cat window perch hammock',
        'dog grooming scissors kit',
        'collapsible dog bowls travel',
        'dog treat pouch training bag',
        'pet feeding mat silicone',
        'dog seat belt harness car',
        'cat scratching post sisal',
        'pet collar light LED',
        'cat litter scoop holder',
        'tick remover tool set'
      ],
    },
    {
      id: 'phone',
      displayName: 'Phone Gadgets',
      hebrewLabel: 'טלפון',
      emoji: '📱',
      description: 'מעמדים, כבלי טעינה, ואביזרים קטנים לסמארטפון',
      weight: 7,
      enabled: true,
      keywords: [
        'magnetic phone stand desk',
        'ring light with stand desktop',
        'phone cleaner kit port',
        'universal phone mount tripod',
        'wireless charging station dock',
        'phone screen magnifier projector',
        'waterproof phone pouch bag',
        'phone cooler fan radiator',
        'phone stand fold laptop',
        'car vents phone mount gravity',
        'table phone holder flexible arm',
        'wireless selfie stick tripod'
      ],
    },
    {
      id: 'computer',
      displayName: 'Computer Accessories',
      hebrewLabel: 'מחשב',
      emoji: '💻',
      description: 'מעמדים, ניקוי, תאורה, ואביזרים שימושיים ללפטופ ומחשב שולחני',
      weight: 6,
      enabled: true,
      keywords: [
        'keyboard cleaning brush kit',
        'monitor light bar screenbar',
        'laptop stand aluminum adjustable',
        'mouse pad wrist rest ergonomic',
        'USB hub multiport adapter USB',
        'web camera cover slide',
        'laptop sleeve bag shockproof',
        'trackball mouse ergonomic wireless',
        'head phone hanger under desk',
        'external SSD hard drive enclosure',
        'USB desk fan quiet',
        'laptop cooling pad stand'
      ],
    },
    {
      id: 'office',
      displayName: 'Office Supplies',
      hebrewLabel: 'משרד',
      emoji: '💼',
      description: 'נוחות עבודה, ארגון שולחן כתיבה, וכלי כתיבה שימושיים',
      weight: 6,
      enabled: true,
      keywords: [
        'desk organizer document holder',
        'paper cutter paper trimmer',
        'cable sleeve zipper management',
        'seat cushion orthopedic memory',
        'desk pad mat large leather',
        'dry erase whiteboard magnetic',
        'foot rest under desk office',
        'notebook journal leather writing',
        'pen organizer desktop holder',
        'book stand holder adjustable',
        'document scanner bag travel',
        'privacy stamp roller cover'
      ],
    },
    {
      id: 'lighting',
      displayName: 'Utility Lighting',
      hebrewLabel: 'תאורה',
      emoji: '💡',
      description: 'תאורת חיישנים, מנורות קריאה, ותאורת אווירה לבית ולשטח',
      weight: 9,
      enabled: true,
      keywords: [
        'motion sensor light strip closet',
        'under cabinet light rechargeable',
        'night light plug in sensor',
        'book light clip on rechargeable',
        'sunset lamp projector light',
        'flame light bulb LED fire',
        'camping flashlight zoomable zoom',
        'fairy lights battery operated LED',
        'toilet bowl night light motion',
        'desk lamp cordless rechargeable',
        'cabinet hinge light LED utility',
        'motion sensor night light wall',
        'projection clock ceiling projector',
        'smart light bulb adapter wifi',
        'solar deck lights outdoor fence',
        'candle warmer lamp top heater',
        'starlight projector galaxy laser',
        'flexible strip light neon sign',
        'mini flashlight keychain USB rechargeable',
        'step light indoor motion wall',
        'candle warmer lamp dimmable wood',
        'sunset lamp projector led usb',
        'motion sensor wall sconce battery',
        'solar gutter lights outdoor sensor',
        'vintage led camping lantern'
      ],
    },
    {
      id: 'garden',
      displayName: 'Garden Tools',
      hebrewLabel: 'גינה',
      emoji: '🪴',
      description: 'השקיה אוטומטית, תמיכה בצמחים, ותאורה דקורטיבית לגינה',
      weight: 8,
      enabled: true,
      keywords: [
        'solar motion light outdoor garden',
        'plant watering spikes self water',
        'garden grafting tool scissors kit',
        'drip irrigation kit system garden',
        'solar fountain pump water bird',
        'plant support clips trellis garden',
        'soil moisture meter sensor meter',
        'grow light strip USB timer',
        'seed starter trays humidity dome',
        'garden kneeler pad cushion foam',
        'bird feeder hanger window bird',
        'garden hose nozzle spray high',
        'solar firefly lights garden pathway',
        'plant root growing box grafting'
      ],
    },
    {
      id: 'bathroom',
      displayName: 'Bathroom Utility',
      hebrewLabel: 'אמבטיה',
      emoji: '🛁',
      description: 'פתרונות לכיור, ניקוז, מעמדי מברשות ונוחות רחצה',
      weight: 7,
      enabled: true,
      keywords: [
        'silicone sink faucet splash guard',
        'toilet brush silicone holder soft',
        'toothpaste squeegee roller wall mount',
        'bath pillow bathtub neck head',
        'hair catcher shower drain protector',
        'bathroom mirror anti fog spray',
        'razor holder wall mount hook',
        'toothbrush holder wall mount electric',
        'soap dispenser wall mount manual',
        'shower head high pressure water',
        'toilet seat lifter handle toilet',
        'bathtub mat non slip suction',
        'toilet paper holder shelf phone',
        'vanity mirror lights LED strip',
        'shower squeegee glass door cleaner',
        'soap saver pad soap dish',
        'bathroom shelf adhesive corner shower',
        'hair dryer holder wall mount',
        'toilet bowl deodorizer gel stamp',
        'waterproof phone box bathroom wall'
      ],
    },
    {
      id: 'laundry',
      displayName: 'Laundry Helpers',
      hebrewLabel: 'כביסה',
      emoji: '🧺',
      description: 'שקיות כביסה, קיפול בגדים, ייבוש וגיהוץ קל',
      weight: 7,
      enabled: true,
      keywords: [
        'wool dryer balls natural softener',
        'collapsible laundry basket space save',
        'socks hanger multi clip drying',
        'clothes folding board shirt flip',
        'laundry detergent sheet dispenser',
        'clothes drying rack sock hanger',
        'laundry beads cup storage bottle',
        'ironing mat pad heat resistant',
        'hanging laundry hamper door bag',
        'washing machine feet pad anti',
        'lint trap net washing machine',
        'shoe washing mesh bag laundry',
        'clothes line portable travel clothes',
        'fabric steamer portable travel iron'
      ],
    },
    {
      id: 'coffee',
      displayName: 'Coffee Gadgets',
      hebrewLabel: 'קפה',
      emoji: '☕',
      description: 'אביזרים להכנה, הקצפה, טחינה ועיצוב כוסות קפה',
      weight: 6,
      enabled: true,
      keywords: [
        'coffee frother electric mixer',
        'coffee grinder manual hand crank',
        'pour over coffee dripper cup',
        'coffee scale timer digital kitchen',
        'coffee tamper espresso powder hammer',
        'coffee distributor leveler tool espresso',
        'reusable coffee capsule pod cup',
        'coffee bag spoon clip',
        'milk frothing pitcher stainless jug',
        'cup warmer mug heater coaster',
        'espresso puck screen reuse metal',
        'coffee mug travel vacuum double'
      ],
    },
    {
      id: 'baby',
      displayName: 'Baby Safety & Care',
      hebrewLabel: 'תינוקות',
      emoji: '👶',
      description: 'מגני בטיחות, אביזרים לעגלה, וטיפוח עדין לתינוקות',
      weight: 5,
      enabled: true,
      keywords: [
        'baby corner protector table guard',
        'cabinet locks child safety strap',
        'silicone baby bib pocket bib',
        'pacifier clip holder leash silicone',
        'baby knee pads crawling helper',
        'baby nasal aspirator hand bulb',
        'baby bath thermometer floating toy',
        'stroller organizer bag drink holder',
        'baby bottle drying rack space',
        'car window shades baby protection',
        'baby finger toothbrush soft silicone',
        'baby food grinder masher bowl',
        'stroller hook hangers aluminum carabiner',
        'baby bath visor cap ears'
      ],
    },
    {
      id: 'kids',
      displayName: 'Kids Toys & Activity',
      hebrewLabel: 'ילדים',
      emoji: '🧸',
      description: 'צעצועי התפתחות, לוחות כתיבה דיגיטליים, ויצירה לילדים',
      weight: 5,
      enabled: true,
      keywords: [
        'magnetic drawing board sketch pad',
        'LCD writing tablet digital board',
        'wooden pattern blocks puzzle',
        'balance stepping stones kids balance',
        'wooden tangram puzzle brain teaser',
        'coloring roll paper wall sticky',
        'coin bank counter digital piggy',
        'rocket launcher toy air pressure',
        'kids binoculars outdoor explorer kit',
        'play tent foldable kids pop',
        'diamond painting stickers kits kids',
        'bath toys organizer mesh bag',
        'water drawing book magic water',
        'projection torch flashlight projector toy'
      ],
    },
    {
      id: 'fitness',
      displayName: 'Fitness Accessories',
      hebrewLabel: 'כושר',
      emoji: '🏋️',
      description: 'גומיות התנגדות, מדי ספורט, עיסוי שרירים ואימון Core',
      weight: 5,
      enabled: true,
      keywords: [
        'resistance bands elastic loop exercise',
        'ab roller wheel abdominal core',
        'jump rope digital counter speed',
        'grip strength trainer hand squeezer',
        'yoga mat strap carrier bag',
        'muscle roller massage stick roller',
        'fitness tracker smart bracelet sleep',
        'water bottle time marker leakproof',
        'cooling towel quick dry sports',
        'push up board stand',
        'running belt bag phone holder',
        'dual exercise sliders gym core'
      ],
    },
    {
      id: 'bicycle',
      displayName: 'Bicycle Gear',
      hebrewLabel: 'אופניים',
      emoji: '🚲',
      description: 'מעמדים לנייד, פנסי USB, מגני בוץ ונוחות רכיבה',
      weight: 5,
      enabled: true,
      keywords: [
        'bicycle phone mount handlebar holder',
        'bike light USB rechargeable head',
        'bike saddle cushion gel seat',
        'bicycle lock chain combination lock',
        'bike tire pump portable mini',
        'cycling gloves gel finger gloves',
        'bike bag frame tube bag',
        'bicycle water bottle cage holder',
        'bike mirror handlebar rearview mirror',
        'bike tool kit multitool wrench',
        'cycling sunglasses polarized sports glasses',
        'bicycle bell ring loud brass'
      ],
    },
    {
      id: 'bbq',
      displayName: 'BBQ Utilities',
      hebrewLabel: 'על האש',
      emoji: '🍖',
      description: 'מברשות ניקוי, מדי טמפרטורה, מגנטים לגריל ונוחות צלייה',
      weight: 6,
      enabled: true,
      keywords: [
        'meat claws shredder pulled pork',
        'grill brush scraper stainless wire',
        'bbq meat thermometer instant read',
        'silicone basting brush oil brush',
        'burger press hamburger patty maker',
        'bbq gloves heat resistant kitchen',
        'charcoal fire starter chimney charcoal',
        'grill lights magnet magnetic base',
        'grill cover waterproof heavy duty',
        'bbq kabob grilling baskets steel',
        'grill tongs locking kitchen tongs',
        'bbq smoker box wood chips'
      ],
    },
    {
      id: 'storage',
      displayName: 'Home Storage',
      hebrewLabel: 'אחסון',
      emoji: '🗃️',
      description: 'קופסאות אחסון שקופות, שקיות ואקום, וארגוניות נעליים',
      weight: 8,
      enabled: true,
      keywords: [
        'vacuum storage bags space saving',
        'shoe storage box clear stackable',
        'storage organizer bins drawer organizer',
        'cosmetic display stand storage drawer',
        'hat organizer hangers clip hooks',
        'hanging shoe organizer closet',
        'tea bag organizer chest box',
        'battery storage organizer case tester',
        'file folder storage box desktop',
        'tissue box holder storage compartment',
        'storage box under bed folding',
        'cable storage box wire management',
        'pill organizer box travel weekly',
        'pen organizer holder storage desk',
        'jewelry roll organizer bag fold',
        'canvas storage basket toy bin',
        'coin holder case storage bank',
        'knife organizer drawer insert tray',
        'cup drying rack counter drainer',
        'blanket storage bag zipper bag'
      ],
    },
    {
      id: 'electronics',
      displayName: 'Electronics Gadgets',
      hebrewLabel: 'אלקטרוניקה',
      emoji: '🔌',
      description: 'מודדים דיגיטליים, מלחמים, מאזניים קטנים וכלי בדיקה ביתיים',
      weight: 7,
      enabled: true,
      keywords: [
        'magnetic cable organizer clip desktop',
        'digital multimeter electrical tester pen',
        'precision tweezers pack',
        'magnifying glass hand loupe lens',
        'digital voice recorder dictaphone record',
        'USB adapter converter type c',
        'wire tracker network cable tester',
        'mini scale jewelry pocket digital',
        'portable laser distance meter rangefinder',
        'electronic scale kitchen luggage weight',
        'wire connector term block solder',
        'heat shrink tubing electrical wire',
        'audio extractor splitter optical audio',
        'bluetooth audio adapter receiver jack',
        'mini stereo amplifier board audio',
        'electronic organizer bag cable travel',
        'battery capacity tester indicator power',
        'voltage test pen non contact'
      ],
    },
    {
      id: 'smarthome',
      displayName: 'Smart Home Controls',
      hebrewLabel: 'בית חכם',
      emoji: '🎛️',
      description: 'שקעי wifi, חיישני טמפרטורה, ומתגים דיגיטליים',
      weight: 7,
      enabled: true,
      keywords: [
        'smart plug socket wifi plug',
        'smart switch button pusher remote',
        'IR remote control smart hub',
        'smart temperature humidity sensor zigbee',
        'smart light switch wall panel',
        'smart bulb holder wifi adapter',
        'window sensor alarm wifi door',
        'smart water leak detector alarm',
        'motion sensor alarm wifi battery',
        'smart door lock card keyless',
        'smart finger bot switch bot',
        'wifi signal repeater range extender',
        'smart led controller wifi dimmer',
        'smart gas leak alarm gas',
        'smart radiator valve thermostat zigbee',
        'smart curtain motor automatic curtain',
        'wifi garage door opener remote',
        'smart siren alarm wifi sounder',
        'zigbee gateway hub wireless bridge',
        'smart air quality monitor co2',
        'mini portable pocket projector smart',
        'smart button pusher wireless bluetooth',
        'zigbee smart radiator actuator valve',
        'smart keybox bluetooth lock wall',
        'wifi gas water valve controller'
      ],
    },
    {
      id: 'emergency',
      displayName: 'Emergency & Safety',
      hebrewLabel: 'חירום',
      emoji: '🚨',
      description: 'רדיו סולארי, שמיכות מילוט, פנסי ראש וכלי הצלה לרכב ולבית',
      weight: 6,
      enabled: true,
      keywords: [
        'emergency survival kit bag gear',
        'hand crank radio solar emergency',
        'tactical pen glass breaker weapon',
        'emergency whistle rescue loud whistle',
        'space blanket emergency thermal foil',
        'emergency ponchos rain coat gear',
        'high visibility safety vest',
        'window breaker seatbelt cutter tool',
        'emergency water filter straw survival',
        'portable chain saw wire pocket',
        'tourniquet band emergency medical belt',
        'led headlamp flashlight head lamp',
        'glow sticks emergency lights chemical',
        'multi tool pliers pocket multitool',
        'fire emergency blanket glass fiber'
      ],
    },
    {
      id: 'security',
      displayName: 'Home Security',
      hebrewLabel: 'אבטחה',
      emoji: '🔒',
      description: 'קופסאות מפתח, מנעולי דלת ניידים, ומעקבי Bluetooth',
      weight: 6,
      enabled: true,
      keywords: [
        'key lock box wall mount',
        'portable door lock travel lock',
        'door stop alarm sensor alert',
        'rf detector anti spy camera',
        'window security locks safety sliding',
        'smart key lock padlock fingerprint',
        'simulated security camera dummy cam',
        'personal alarm keychain safe sound',
        'key finder bluetooth locator tracker',
        'rfid blocking card sleeves protection',
        'security lock cable steel cable',
        'combination padlock luggage lock number',
        'home lock box keys wall',
        'door reinforcement lock secure latch',
        'magnetic window sensors alarm sounder'
      ],
    },
    {
      id: 'photography',
      displayName: 'Photography Accessories',
      hebrewLabel: 'צילום',
      emoji: '📷',
      description: 'מעמדי חצובה, תאורת רינג, וציוד ניקוי עדשות',
      weight: 4,
      enabled: true,
      keywords: [
        'mini light box photo studio',
        'photo background paper studio backdrop',
        'lens cleaning kit pen air',
        'universal diffuser softbox flash reflector',
        'camera wrist strap paracord neck',
        'desk mount camera stand pole',
        'camera tripod mount phone mount',
        'lens filter case pouch wallet',
        'green screen background chroma key',
        'ring light phone selfie clip'
      ],
    },
    {
      id: 'tools',
      displayName: 'Hand Tools',
      hebrewLabel: 'כלים',
      emoji: '🔧',
      description: 'מברגים מגנטיים, גלאי מתכות לקיר, ומחלצי ברגים פגומים',
      weight: 7,
      enabled: true,
      keywords: [
        'magnetic screwdriver set precision kits',
        'universal socket wrench multi tool',
        'digital pocket scale gram scale',
        'stud finder wall scanner detector',
        'magnetic pickup tool telescoping stick',
        'step drill bit wood drilling',
        'deburring tool hand debur scraper',
        'flexible extension drill bit hose',
        'thread pitch gauge metric screw',
        'center punch automatic spring loaded',
        'tap and die set screw',
        'wire twist tool drill driver',
        'automatic wire stripper crimper plier',
        'socket adapter impact driver hex',
        'magnetic screwdriver ring magnetizer ring',
        'hand riveter gun rivet tool',
        'pocket hole jig kit joinery',
        'right angle drill adapter hex',
        'level tool pocket level bubble',
        'hex key wrench set allen'
      ],
    },
    {
      id: 'car_care',
      displayName: 'Car Care & Polish',
      hebrewLabel: 'טיוח הרכב',
      emoji: '🧽',
      description: 'מטליות ייבוש, ערכות פוליש וטיפוח פנים וחוץ הרכב',
      weight: 8,
      enabled: true,
      keywords: [
        'microfiber car drying towel towel',
        'car washing mitt chenille glove',
        'windshield glass water repellent spray',
        'clay bar car detailing clean',
        'wheel rim cleaning brush wire',
        'scratch repair cloth wax compound',
        'leather cleaner conditioner cream seat',
        'foam lance soap bottle spray',
        'micro fiber wax applicator pads',
        'car cleaning brush vent detailing',
        'car wash squeeze sprayer pump',
        'plastic trim restorer agent polish',
        'car interior cleaning gel slime',
        'buffing pads drill polishing pad'
      ],
    },
  ],
};

export const discoveryConfig: DiscoveryConfig = {
  strategies: legacyDiscoveryStrategies,
  categories: discoveryLibraryV2.categories,
};
