import { Money } from '@/features/products/types';

/**
 * Escapes special XML characters to prevent Telegram HTML parse errors.
 */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Formats product price for user display.
 */
export function formatPriceForTelegram(amount: number, currency: string): string {
  const cleanCurrency = currency.toUpperCase();
  const formattedAmount = amount % 1 === 0 ? String(Math.floor(amount)) : amount.toFixed(2);
  if (cleanCurrency === 'ILS') {
    return `₪${formattedAmount}`;
  }
  if (cleanCurrency === 'USD') {
    return `$${formattedAmount}`;
  }
  return `${formattedAmount} ${currency}`;
}

/**
 * Assembles the final post into safe HTML using dynamic values.
 */
export function buildTelegramHtmlPost(input: {
  headline: string;
  body: string;
  cta: string;
  affiliateUrl: string;
  price: Money;
  originalPrice?: Money;
  discountPercent?: number;
}): string {
  const escapedHeadline = escapeHtml(input.headline.trim());
  const escapedBody = escapeHtml(input.body.trim());
  const escapedCta = escapeHtml(input.cta.trim());

  const formattedPrice = formatPriceForTelegram(input.price.amount, input.price.currency);
  const escapedPrice = escapeHtml(formattedPrice);

  let priceLine = `💰 <b>${escapedPrice}</b>`;

  const hasOriginalPrice =
    input.originalPrice &&
    input.originalPrice.amount > input.price.amount &&
    input.originalPrice.currency === input.price.currency;

  if (hasOriginalPrice && input.originalPrice) {
    const formattedOriginal = formatPriceForTelegram(
      input.originalPrice.amount,
      input.originalPrice.currency
    );
    const escapedOriginal = escapeHtml(formattedOriginal);
    priceLine = `💰 <b>${escapedPrice}</b> במקום <s>${escapedOriginal}</s>`;
    if (input.discountPercent !== undefined && input.discountPercent > 0) {
      priceLine += ` · ${input.discountPercent}% הנחה`;
    }
  }

  // Assemble the parts. Ensure standard blank line spacing and keep the affiliate URL raw on the final line.
  return `<b>${escapedHeadline}</b>\n\n${escapedBody}\n\n${priceLine}\n\n${escapedCta}\n${input.affiliateUrl.trim()}`;
}

/**
 * Strips ONLY the HTML formatting tags generated by buildTelegramHtmlPost
 * and decodes the known HTML entities escaped by escapeHtml.
 */
export function stripTelegramHtml(html: string): string {
  let text = html
    .replace(/<\/?b>/g, '')
    .replace(/<\/?s>/g, '');

  text = text
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');

  return text;
}

/**
 * Determines whether a Telegram API error string is related to HTML tag parsing.
 */
export function isTelegramHtmlParseError(error: string): boolean {
  const normalized = error.toLowerCase();
  return (
    normalized.includes("can't parse entities") ||
    normalized.includes('must be escaped') ||
    normalized.includes("can't parse")
  );
}
